version: "3.8"

services:
   mysql: 
    build:
      context: .
    ports:
       - 3306:3306
   backend:
     build: 
       context: ./api
     ports:
      - "8000:8000"
    #  environment:
    #    - ALLOW_EMPTY_PASSWORD=yes
    #    - SYMFONY_DATABASE_HOST=mysql
    #    - SYMFONY_DATABASE_USER=marvin
    #    - SYMFONY_DATABASE_PASSWORD=nsapool421
    #    - SYMFONY_DATABASE_NAME=nsapool
     volumes:
      - './api:/api'
      - '/api/vendor'
     depends_on:
      - mysql
   frontend:
    build:
      context: ./frontend
    ports: 
      - "3000:3000"
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    stdin_open: true
   portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports: 
      - "5555:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
